name: cpp-linter
on:
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          install-linux-dependencies: true
          version: 3-latest
          version-sdl-image: 3-latest

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            mpv libvulkan1 libvulkan-dev vulkan-tools \
            wayland-protocols libplacebo-dev libsystemd-dev \
            plasma-wayland-protocols meson ffmpeg \
            libavcodec-dev libavformat-dev libavfilter-dev \
            libass-dev libwayland-dev

      - name: Run Ninja
        run: | 
          git submodule update --init --recursive
          python3 dev/download_cef.py
          cmake -B build -G Ninja -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake --build build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: build-output
          path: build/

  cpp-linter:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Download build artificats
        uses: actions/download-artifact@v6
        with:
          name: build-output
          path: build/

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file' # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          lines-changed-only: true
          files-changed-only: true


      - name: Failure
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
